"""
PR review summary generation.

Uses GPT-4o-mini to produce a markdown summary of all findings,
grouped by agent and severity. Falls back to a template-based
summary if the LLM call fails.
"""

from __future__ import annotations

import json
from collections import Counter

import structlog
from openai import AsyncOpenAI

from agents.prompts import SUMMARY_SYSTEM_PROMPT, SUMMARY_USER_PROMPT
from shared.config.settings import get_settings

logger = structlog.get_logger(__name__)


def _template_summary(findings: list[dict]) -> str:
    """Generate a template-based summary without LLM (fallback)."""
    total = len(findings)
    if total == 0:
        return (
            "## AI Code Review Summary\n\n✅ **No issues found.** The code looks good!"
        )

    # Count by severity
    severity_counts = Counter(f.get("severity", "info") for f in findings)
    agent_counts = Counter(f.get("agent", "unknown") for f in findings)

    # Count affected files
    files = set(
        f.get("file_path", f.get("file", ""))
        for f in findings
        if f.get("file_path") or f.get("file")
    )

    lines = [
        "## AI Code Review Summary",
        f"**{total} findings** across {len(files)} files",
        "",
    ]

    # Critical issues (errors)
    errors = [f for f in findings if f.get("severity") == "error"]
    if errors:
        lines.append("### 🔴 Critical Issues")
        for e in errors[:10]:
            file_path = e.get("file_path", e.get("file", "unknown"))
            line_num = e.get("line_number", e.get("line", ""))
            line_ref = f":{line_num}" if line_num else ""
            lines.append(f"- `{file_path}{line_ref}` — {e.get('message', '')}")
        lines.append("")

    # Warnings
    warnings = [f for f in findings if f.get("severity") == "warning"]
    if warnings:
        lines.append("### 🟡 Warnings")
        for w in warnings[:10]:
            file_path = w.get("file_path", w.get("file", "unknown"))
            line_num = w.get("line_number", w.get("line", ""))
            line_ref = f":{line_num}" if line_num else ""
            lines.append(f"- `{file_path}{line_ref}` — {w.get('message', '')}")
        lines.append("")

    # By category
    lines.append("### By Category")
    for agent, count in agent_counts.most_common():
        lines.append(f"- **{agent.title()}**: {count} findings")
    lines.append("")

    # By severity
    lines.append("### By Severity")
    for severity in ["error", "warning", "info", "suggestion"]:
        count = severity_counts.get(severity, 0)
        if count > 0:
            emoji = {
                "error": "🔴",
                "warning": "🟡",
                "info": "🔵",
                "suggestion": "💡",
            }.get(severity, "")
            lines.append(f"- {emoji} **{severity.title()}**: {count}")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by AI Code Review Pipeline*")

    return "\n".join(lines)


async def generate_summary(findings: list[dict]) -> str:
    """
    Generate a markdown review summary using GPT-4o-mini.

    Falls back to a template-based summary if the LLM call fails.
    """
    settings = get_settings()

    if not findings:
        return (
            "## AI Code Review Summary\n\n✅ **No issues found.** The code looks good!"
        )

    # Try LLM-generated summary
    try:
        client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

        # Prepare a compact version of findings for the prompt
        compact_findings = [
            {
                "agent": f.get("agent", "unknown"),
                "file": f.get("file_path", f.get("file", "")),
                "line": f.get("line_number", f.get("line")),
                "severity": f.get("severity", "info"),
                "message": f.get("message", ""),
            }
            for f in findings
        ]

        user_prompt = SUMMARY_USER_PROMPT.format(
            findings_json=json.dumps(compact_findings, indent=2)
        )

        response = await client.chat.completions.create(
            model=settings.OPENAI_MODEL,
            messages=[
                {"role": "system", "content": SUMMARY_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=2048,
        )

        summary = response.choices[0].message.content
        if summary:
            logger.info("llm_summary_generated")
            return summary

    except Exception as exc:
        logger.warning("llm_summary_failed_using_template", error=str(exc))

    # Fallback to template
    return _template_summary(findings)
