name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: infra/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ai-reviewer-cluster --region us-east-1

      - name: Update Deployments
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/ai-pr-reviewer:main"
          IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          kubectl set image deployment/celery-worker celery-worker=$IMAGE -n codereview
          kubectl set image deployment/gateway gateway=$IMAGE -n codereview
          kubectl set image deployment/webhook webhook=$IMAGE -n codereview
          kubectl set image deployment/orchestrator orchestrator=$IMAGE -n codereview
          kubectl set image deployment/reviewer reviewer=$IMAGE -n codereview
          kubectl set image deployment/learner learner=$IMAGE -n codereview
